/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaonei.struts.action;

import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.xiaonei.bean.Album;
import com.xiaonei.bean.Photo;
import com.xiaonei.bean.Users;
import com.xiaonei.service.inter.AlbumServiceInter;
import com.xiaonei.struts.form.AlbumForm;
import com.xiaonei.utils.MyTools;


public class AlbumAction extends DispatchAction {

	private AlbumServiceInter albumService;
	
	public ActionForward myAlbumUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goMyAlbumUI");
	}
	
	//跳转到添加一个相册的页面 addAlbumUI
	public ActionForward addAlbumUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goAddAlbumUI");
	}
	
	//跳转到给相册添加图片的页面 addPhotoUI
	//创建一个相册
	public ActionForward addPhotoUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//完成创建相册的任务..
		//从表单中获取创建相册的信息(name,descript,whosee)
		AlbumForm albumForm=(AlbumForm)form;
		//创建一个Album 对象
		Album album=new Album();
		album.setCreTime(new Date());
		album.setDescript(albumForm.getDescript());
		album.setName(albumForm.getName());
		album.setUpdTime(new Date());
		Users loginUser=(Users) request.getSession().getAttribute("loginuser");
		album.setUsers(loginUser);//这里要指定该相册是属于谁的?
		albumService.save(album);
		request.setAttribute("album", album);
		
		return mapping.findForward("goAddPhotoUI");
	}
	
	//跳转到当前这个相册 oneAlbumUI
	public ActionForward oneAlbumUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		System.out.println("oneAlbumUI...");
		//这里，我们要完成把图片上传到服务器，并保存记录到Photo对象
		//先考虑用户上传一张图片的情况
		AlbumForm albumForm=(AlbumForm)form;
		Users loginUser=(Users) request.getSession().getAttribute("loginuser");
		FormFile photo1=albumForm.getPhoto1();
		
		if(!"".equals(photo1.getFileName())){
			//说明用户上传了第一张照片
			//把图片上传上去
			//在把信息保存到数据库
			
			String newFileName=MyTools.uploadPhoto(request, photo1,loginUser.getId()+"" , albumForm.getId());
			Photo myPhoto1=new Photo();
			myPhoto1.setAddTime(new Date());
			myPhoto1.setAlbum
			((Album)albumService.findById(Album.class, Integer.valueOf(albumForm.getId())));//该相片属于哪个相册
			myPhoto1.setPhoto(newFileName);
			//这句话就是把信息保存到数据库
			albumService.save(myPhoto1);
			
		}
		
		FormFile photo2=albumForm.getPhoto2();
		
		if(!"".equals(photo2.getFileName())){
			//说明用户上传了第一张照片
			//把图片上传上去
			//在把信息保存到数据库
			String newFileName=MyTools.uploadPhoto(request, photo2,loginUser.getId()+"" , albumForm.getId());
			Photo myPhoto2=new Photo();
			myPhoto2.setAddTime(new Date());
			myPhoto2.setAlbum
			((Album)albumService.findById(Album.class, Integer.valueOf(albumForm.getId())));//该相片属于哪个相册
			myPhoto2.setPhoto(newFileName);
			//这句话就是把信息保存到数据库
			albumService.save(myPhoto2);
			
		}
		
		//把该相册要显示的图片放入list ,准备显示.(考虑分页)
		//Album curAlbum=(Album) albumService.findById(Album.class,Integer.valueOf(albumForm.getId()) );
		//Set photoList=  curAlbum.getPhotos();
		List photoList=albumService.getResult("from Photo where album.id=?", new Object[]{Integer.valueOf(albumForm.getId())});
		request.setAttribute("photoList", photoList);
		return mapping.findForward("goOneAlbumUI");
	}
	//onePhotoUI 跳转到一张一张的观看该相册图片的界面
	public ActionForward onePhotoUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goOnePhotoUI");
	}

	public void setAlbumService(AlbumServiceInter albumService) {
		this.albumService = albumService;
	}
}