/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaonei.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.xiaonei.bean.Users;
import com.xiaonei.service.inter.UserServiceInter;
import com.xiaonei.web.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-22-2010
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" parameter="flag" scope="request"
 */
public class LoginAction extends DispatchAction {
	
	private UserServiceInter userService;
	
	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	//响应用户注销请求
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//把当前的网站的session情况
		request.getSession().invalidate();
		return mapping.findForward("goIndexUI");
	}
	
	//响应用户登录请求
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		//取出用户输入的电子邮箱，和密码,然后到数据库去验证.
		//第一种方法[分析可从mvc 的角度看,我们不欣赏这种做法，mvc action是c角色，因此应当尽可能的把业务逻辑写的service]
		Users user=new Users();
		user.setEmail(userForm.getEmail());
		user.setPwd(userForm.getPwd());
		System.out.println("email =" +userForm.getEmail()+" pwd="+userForm.getPwd());
		user=userService.check(user);
		if(user!=null){
			//用户合法,必须把该用户bean放入session域对象
			request.getSession().setAttribute("loginuser", user);
			return mapping.findForward("goHomeUI");
		}else{
			//不合法
			return mapping.findForward("goIndexUI");
		}
		
	}
}