/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaonei.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.xiaonei.bean.Users;
import com.xiaonei.service.inter.UserServiceInter;
import com.xiaonei.utils.MyTools;
import com.xiaonei.web.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-22-2010
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class ProfileAction extends DispatchAction {
	
	private UserServiceInter userService;
	//跳转到个人主页
	public ActionForward goHomePageUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goHomePageUI");
	}
	
	//跳转到上传头像的界面 uploadPhotoUI
	public ActionForward uploadPhotoUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goUploadPhotoUI");
	}
	
	//真的上传一个头像
	public ActionForward uploadPhoto(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		Users loginUser=(Users) request.getSession().getAttribute("loginuser");
		UserForm userForm= (UserForm)form;
		FormFile myPhoto=userForm.getMyphoto();
		
		//把该头像上传到服务器的某个目录下 [xiaoneinew/images/用户编号/head/头像图片]
		
		//***
		String newHeadPhoto=MyTools.uploadHead(request, myPhoto, loginUser.getId()+"");
		//得到当前用户[从session取出]
		
		//修改当前用的头像名称
		loginUser.setPhoto(newHeadPhoto);
		userService.update(loginUser);
		//loginUser.setPhoto(userForm.getMyphoto());
		return mapping.findForward("goUploadPhotoUI");
	}

	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}
}